#$clientid = <Spotify API client ID here>
$clientid = "59bdc1a1e8e3426aad253f43646aa739"

$MLBrootURL = "https://www.mlb.com/entertainment/walk-up"
$TeamShortNames = @('ari','atl','bal','bos','chc','cws','cin','cle','col','det','hou','kc','laa','lad','mia','mil','min','nym','nyy','oak','phi','pit','sd','sf','sea','stl','tb','tex','tor','wsh') 

#Request URI to a rave gif using to grab an access token (it will be shown in the URL)
$AuthUri = "https://accounts.spotify.com/en/authorize?" +
           "client_id=$clientid" +                                                                                    
           "&redirect_uri=https://media.giphy.com/media/9YlhdI9SSP0Qw/giphy.gif" +         
           "&scope=playlist-modify-public playlist-modify-private playlist-read-private playlist-read-collaborative" +
           "&response_type=token"

#Create a form based browser object to navigate to the rave gif
Add-Type -AssemblyName System.Windows.Forms
$FormProperties = @{
    Size = New-Object System.Drawing.Size(850, 675)
    StartPosition = "CenterScreen"
}
$Form = New-Object System.Windows.Forms.Form -Property $FormProperties
$BrowserProperties = @{
    Dock = "Fill"
}
$Browser = New-Object System.Windows.Forms.WebBrowser -Property $BrowserProperties
$Form.Controls.Add($Browser)
$Browser.Navigate($AuthUri)
$Form.Add_Shown({$Form.Activate()})
$Form.ShowDialog()

#RegEx to grab your access token from the URI generated by accessing the rave gif
if ($Browser.url.Fragment -match "access_token=(.*)&token") 
    {
        $AccessToken = $Matches[1]
    }

$UserUri = "https://api.spotify.com/v1/me"
$BearerToken = "Bearer $AccessToken"
$HeaderValue = @{Authorization = $BearerToken}
$UserAccount = (Invoke-RestMethod -Uri $UserUri -Method Get -ContentType application\json -Headers $HeaderValue).href


#Build the Playlist, get the playlist ID
$PlaylistUri = $UserAccount + "/playlists"


foreach ($Team in $TeamShortNames)
{

  $TeamURI = $MLBrootURL + "/" + $Team
  $r = Invoke-WebRequest $TeamURI

  $ExtraPlaylistName = $r.ParsedHTML.title
  $Pipe = $ExtraPlaylistName.IndexOf("|")
  $TeamFullName = $ExtraPlaylistName.Substring(0,$Pipe)
  $PlayListName = $TeamFullName + "Walk Up Songs"

  $NewPlaylist = @{
      name = $PlayListName
      public = "true"
  } | ConvertTo-Json

  $PlaylistID = Invoke-RestMethod -Uri $PlaylistUri -Method Post -ContentType application/json -Headers $HeaderValue -Body $NewplayList

  $SpotifySongLinks = ($r.Links | Where-Object {$_ -like "*spotify*"}).href
  $SpotifySongIDs = foreach ($SongLink in $SpotifySongLinks) {$SongLink.Substring($SongLink.Length - 22)}
  $CombinedSongIDs = $SpotifySongIDs -join ","

  $AddTrackUri = $UserAccount + "/playlists/" + $PlaylistID.id + "/tracks?position=0&uris=$CombinedSongIDs"

  Invoke-RestMethod -Uri $AddTrackUri -Method Post -ContentType application/json -Headers $HeaderValue
  Start-Sleep 1

}
